fisc-erp-connector:
  currency:
    AUD: 1
    USD: 3
    JPY: 5
    1: AUD
    3: USD
    5: JPY
  country:
    AF: _afghanistan
    AX: _alandIslands
    AL: _albania
    DZ: _algeria
    AS: _americanSamoa
    AD: _andorra
    AO: _angola
    AI: _anguilla
    AQ: _antarctica
    AG: _antiguaAndBarbuda
    AR: _argentina
    AM: _armenia
    AW: _aruba
    AU: _australia
    AT: _austria
    AZ: _azerbaijan
    BS: _bahamas
    BH: _bahrain
    BD: _bangladesh
    BB: _barbados
    BY: _belarus
    BE: _belgium
    BZ: _belize
    BJ: _benin
    BM: _bermuda
    BT: _bhutan
    BO: _bolivia
    BQ: _bonaireSaintEustatiusAndSaba
    BA: _bosniaAndHerzegovina
    BW: _botswana
    BV: _bouvetIsland
    BR: _brazil
    IO: _britishIndianOceanTerritory
    BN: _bruneiDarussalam
    BG: _bulgaria
    BF: _burkinaFaso
    BI: _burundi
    KH: _cambodia
    CM: _cameroon
    CA: _canada
    IC: _canaryIslands
    CV: _capeVerde
    KY: _caymanIslands
    CF: _centralAfricanRepublic
    EA: _ceutaAndMelilla
    TD: _chad
    CL: _chile
    CN: _china
    CX: _christmasIsland
    CC: _cocosKeelingIslands
    CO: _colombia
    KM: _comoros
    CD: _congoDemocraticPeoplesRepublic
    CG: _congoRepublicOf
    CK: _cookIslands
    CR: _costaRica
    CI: _coteDIvoire
    HR: _croatiaHrvatska
    CU: _cuba
    CW: _curacao
    CY: _cyprus
    CZ: _czechRepublic
    DK: _denmark
    DJ: _djibouti
    DM: _dominica
    DO: _dominicanRepublic
    TL: _eastTimor
    EC: _ecuador
    EG: _egypt
    SV: _elSalvador
    GQ: _equatorialGuinea
    ER: _eritrea
    EE: _estonia
    ET: _ethiopia
    FK: _falklandIslands
    FO: _faroeIslands
    FJ: _fiji
    FI: _finland
    FR: _france
    GF: _frenchGuiana
    PF: _frenchPolynesia
    TF: _frenchSouthernTerritories
    GA: _gabon
    GM: _gambia
    GE: _georgia
    DE: _germany
    GH: _ghana
    GI: _gibraltar
    GR: _greece
    GL: _greenland
    GD: _grenada
    GP: _guadeloupe
    GU: _guam
    GT: _guatemala
    GG: _guernsey
    GN: _guinea
    GW: _guineaBissau
    GY: _guyana
    HT: _haiti
    HM: _heardAndMcDonaldIslands
    VA: _holySeeCityVaticanState
    HN: _honduras
    HK: _hongKong
    HU: _hungary
    IS: _iceland
    IN: _india
    ID: _indonesia
    IR: _iranIslamicRepublicOf
    IQ: _iraq
    IE: _ireland
    IM: _isleOfMan
    IL: _israel
    IT: _italy
    JM: _jamaica
    JP: _japan
    JE: _jersey
    JO: _jordan
    KZ: _kazakhstan
    KE: _kenya
    KI: _kiribati
    KP: _koreaDemocraticPeoplesRepublic
    KR: _koreaRepublicOf
    XK: _kosovo
    KW: _kuwait
    KG: _kyrgyzstan
    LA: _laoPeoplesDemocraticRepublic
    LV: _latvia
    LB: _lebanon
    LS: _lesotho
    LR: _liberia
    LY: _libya
    LI: _liechtenstein
    LT: _lithuania
    LU: _luxembourg
    MO: _macau
    MK: _macedonia
    MG: _madagascar
    MW: _malawi
    MY: _malaysia
    MV: _maldives
    ML: _mali
    MT: _malta
    MH: _marshallIslands
    MQ: _martinique
    MR: _mauritania
    MU: _mauritius
    YT: _mayotte
    MX: _mexico
    FM: _micronesiaFederalStateOf
    MD: _moldovaRepublicOf
    MC: _monaco
    MN: _mongolia
    ME: _montenegro
    MS: _montserrat
    MA: _morocco
    MZ: _mozambique
    MM: _myanmar
    NA: _namibia
    NR: _nauru
    NP: _nepal
    NL: _netherlands
    NC: _newCaledonia
    NZ: _newZealand
    NI: _nicaragua
    NE: _niger
    NG: _nigeria
    NU: _niue
    NF: _norfolkIsland
    MP: _northernMarianaIslands
    NO: _norway
    OM: _oman
    PK: _pakistan
    PW: _palau
    PA: _panama
    PG: _papuaNewGuinea
    PY: _paraguay
    PE: _peru
    PH: _philippines
    PN: _pitcairnIsland
    PL: _poland
    PT: _portugal
    PR: _puertoRico
    QA: _qatar
    RE: _reunionIsland
    RO: _romania
    RU: _russianFederation
    RW: _rwanda
    BL: _saintBarthelemy
    SH: _saintHelena
    KN: _saintKittsAndNevis
    LC: _saintLucia
    MF: _saintMartin
    VC: _saintVincentAndTheGrenadines
    WS: _samoa
    SM: _sanMarino
    ST: _saoTomeAndPrincipe
    SA: _saudiArabia
    SN: _senegal
    RS: _serbia
    SC: _seychelles
    SL: _sierraLeone
    SG: _singapore
    SX: _sintMaarten
    SK: _slovakRepublic
    SI: _slovenia
    SB: _solomonIslands
    SO: _somalia
    ZA: _southAfrica
    GS: _southGeorgia
    SS: _southSudan
    ES: _spain
    LK: _sriLanka
    PS: _stateOfPalestine
    PM: _stPierreAndMiquelon
    SD: _sudan
    SR: _suriname
    SJ: _svalbardAndJanMayenIslands
    SZ: _swaziland
    SE: _sweden
    CH: _switzerland
    SY: _syrianArabRepublic
    TW: _taiwan
    TJ: _tajikistan
    TZ: _tanzania
    TH: _thailand
    TG: _togo
    TK: _tokelau
    TO: _tonga
    TT: _trinidadAndTobago
    TN: _tunisia
    TR: _turkey
    TM: _turkmenistan
    TC: _turksAndCaicosIslands
    TV: _tuvalu
    UG: _uganda
    UA: _ukraine
    AE: _unitedArabEmirates
    GB: _unitedKingdom
    US: _unitedStates
    UY: _uruguay
    UM: _uSMinorOutlyingIslands
    UZ: _uzbekistan
    VU: _vanuatu
    VE: _venezuela
    VN: _vietnam
    VG: _virginIslandsBritish
    VI: _virginIslandsUSA
    WF: _wallisAndFutunaIslands
    EH: _westernSahara
    YE: _yemen
    ZM: _zambia
    ZW: _zimbabwe
    _afghanistan: AF
    _alandIslands: AX
    _albania: AL
    _algeria: DZ
    _americanSamoa: AS
    _andorra: AD
    _angola: AO
    _anguilla: AI
    _antarctica: AQ
    _antiguaAndBarbuda: AG
    _argentina: AR
    _armenia: AM
    _aruba: AW
    _australia: AU
    _austria: AT
    _azerbaijan: AZ
    _bahamas: BS
    _bahrain: BH
    _bangladesh: BD
    _barbados: BB
    _belarus: BY
    _belgium: BE
    _belize: BZ
    _benin: BJ
    _bermuda: BM
    _bhutan: BT
    _bolivia: BO
    _bonaireSaintEustatiusAndSaba: BQ
    _bosniaAndHerzegovina: BA
    _botswana: BW
    _bouvetIsland: BV
    _brazil: BR
    _britishIndianOceanTerritory: IO
    _bruneiDarussalam: BN
    _bulgaria: BG
    _burkinaFaso: BF
    _burundi: BI
    _cambodia: KH
    _cameroon: CM
    _canada: CA
    _canaryIslands: IC
    _capeVerde: CV
    _caymanIslands: KY
    _centralAfricanRepublic: CF
    _ceutaAndMelilla: EA
    _chad: TD
    _chile: CL
    _china: CN
    _christmasIsland: CX
    _cocosKeelingIslands: CC
    _colombia: CO
    _comoros: KM
    _congoDemocraticPeoplesRepublic: CD
    _congoRepublicOf: CG
    _cookIslands: CK
    _costaRica: CR
    _coteDIvoire: CI
    _croatiaHrvatska: HR
    _cuba: CU
    _curacao: CW
    _cyprus: CY
    _czechRepublic: CZ
    _denmark: DK
    _djibouti: DJ
    _dominica: DM
    _dominicanRepublic: DO
    _eastTimor: TL
    _ecuador: EC
    _egypt: EG
    _elSalvador: SV
    _equatorialGuinea: GQ
    _eritrea: ER
    _estonia: EE
    _ethiopia: ET
    _falklandIslands: FK
    _faroeIslands: FO
    _fiji: FJ
    _finland: FI
    _france: FR
    _frenchGuiana: GF
    _frenchPolynesia: PF
    _frenchSouthernTerritories: TF
    _gabon: GA
    _gambia: GM
    _georgia: GE
    _germany: DE
    _ghana: GH
    _gibraltar: GI
    _greece: GR
    _greenland: GL
    _grenada: GD
    _guadeloupe: GP
    _guam: GU
    _guatemala: GT
    _guernsey: GG
    _guinea: GN
    _guineaBissau: GW
    _guyana: GY
    _haiti: HT
    _heardAndMcDonaldIslands: HM
    _holySeeCityVaticanState: VA
    _honduras: HN
    _hongKong: HK
    _hungary: HU
    _iceland: IS
    _india: IN
    _indonesia: ID
    _iranIslamicRepublicOf: IR
    _iraq: IQ
    _ireland: IE
    _isleOfMan: IM
    _israel: IL
    _italy: IT
    _jamaica: JM
    _japan: JP
    _jersey: JE
    _jordan: JO
    _kazakhstan: KZ
    _kenya: KE
    _kiribati: KI
    _koreaDemocraticPeoplesRepublic: KP
    _koreaRepublicOf: KR
    _kosovo: XK
    _kuwait: KW
    _kyrgyzstan: KG
    _laoPeoplesDemocraticRepublic: LA
    _latvia: LV
    _lebanon: LB
    _lesotho: LS
    _liberia: LR
    _libya: LY
    _liechtenstein: LI
    _lithuania: LT
    _luxembourg: LU
    _macau: MO
    _macedonia: MK
    _madagascar: MG
    _malawi: MW
    _malaysia: MY
    _maldives: MV
    _mali: ML
    _malta: MT
    _marshallIslands: MH
    _martinique: MQ
    _mauritania: MR
    _mauritius: MU
    _mayotte: YT
    _mexico: MX
    _micronesiaFederalStateOf: FM
    _moldovaRepublicOf: MD
    _monaco: MC
    _mongolia: MN
    _montenegro: ME
    _montserrat: MS
    _morocco: MA
    _mozambique: MZ
    _myanmar: MM
    _namibia: NA
    _nauru: NR
    _nepal: NP
    _netherlands: NL
    _newCaledonia: NC
    _newZealand: NZ
    _nicaragua: NI
    _niger: NE
    _nigeria: NG
    _niue: NU
    _norfolkIsland: NF
    _northernMarianaIslands: MP
    _norway: NO
    _oman: OM
    _pakistan: PK
    _palau: PW
    _panama: PA
    _papuaNewGuinea: PG
    _paraguay: PY
    _peru: PE
    _philippines: PH
    _pitcairnIsland: PN
    _poland: PL
    _portugal: PT
    _puertoRico: PR
    _qatar: QA
    _reunionIsland: RE
    _romania: RO
    _russianFederation: RU
    _rwanda: RW
    _saintBarthelemy: BL
    _saintHelena: SH
    _saintKittsAndNevis: KN
    _saintLucia: LC
    _saintMartin: MF
    _saintVincentAndTheGrenadines: VC
    _samoa: WS
    _sanMarino: SM
    _saoTomeAndPrincipe: ST
    _saudiArabia: SA
    _senegal: SN
    _serbia: RS
    _seychelles: SC
    _sierraLeone: SL
    _singapore: SG
    _sintMaarten: SX
    _slovakRepublic: SK
    _slovenia: SI
    _solomonIslands: SB
    _somalia: SO
    _southAfrica: ZA
    _southGeorgia: GS
    _southSudan: SS
    _spain: ES
    _sriLanka: LK
    _stateOfPalestine: PS
    _stPierreAndMiquelon: PM
    _sudan: SD
    _suriname: SR
    _svalbardAndJanMayenIslands: SJ
    _swaziland: SZ
    _sweden: SE
    _switzerland: CH
    _syrianArabRepublic: SY
    _taiwan: TW
    _tajikistan: TJ
    _tanzania: TZ
    _thailand: TH
    _togo: TG
    _tokelau: TK
    _tonga: TO
    _trinidadAndTobago: TT
    _tunisia: TN
    _turkey: TR
    _turkmenistan: TM
    _turksAndCaicosIslands: TC
    _tuvalu: TV
    _uganda: UG
    _ukraine: UA
    _unitedArabEmirates: AE
    _unitedKingdom: GB
    _unitedStates: US
    _uruguay: UY
    _uSMinorOutlyingIslands: UM
    _uzbekistan: UZ
    _vanuatu: VU
    _venezuela: VE
    _vietnam: VN
    _virginIslandsBritish: VG
    _virginIslandsUSA: VI
    _wallisAndFutunaIslands: WF
    _westernSahara: EH
    _yemen: YE
    _zambia: ZM
    _zimbabwe: ZW
  bankAccountRef:
    '[PTY HAMS Stripe JPY]': "Pty JPY-5013"
    '[PTY HAMS Stripe AU-USD]': "Pty USD-2048"
    '[PTY HAMS Stripe CA-USD]': "Pty USD-7532"
    '[PTY HAMS Stripe NL-USD]': "Pty USD-7532"
    '[PTY HAMS Stripe US-USD]': "Pty USD-7532"
    '[PTY HAMS Paypal USD]': "Pty USD-3898"
    '[PTY HAMS Paypal JPY]': "Pty JPY-8040"
    '[PTY WIRE JPY]': "Pty JPY-8040"
    '[PTY WIRE US-USD]': "Pty USD-2048"
    '[PTY WIRE AU-AUD]': "Pty AUD-2014"
    '[PTY WIRE EUR]': "Pty EUR-2030"
  paymentMethod:
    1: "PAIDONACCOUNT"
    2: "PAID ON TERMS"
    3: "PAID_ON_TERMS"
    4: "PAIDONTERMS"
    5: "PAID_CREDIT"
    6: "PAIDCREDIT"
    7: "PAIDCC"
    8: "PAID"
    9: "PAIDPAYPAL"