package bamboo;

import com.atlassian.bamboo.specs.api.builders.project.Project;
import lombok.experimental.UtilityClass;

import java.util.HashMap;
import java.util.Map;
/**
 * These are all of the constants that you would need to change for your specific service.
 *
 * <p>Note not all of these fields can be automatically generated by instant micros because of collisions with plan
 * keys, names, etc.
 */
@UtilityClass
@SuppressWarnings("WeakerAccess")
final class Constants {
    static final String PROJECT_KEY = "FS";
    static final String PROJECT_NAME = "Finance Systems";
    static final Project PROJECT = new Project()
            .key(PROJECT_KEY)
            .name(PROJECT_NAME);

    public static final String repositoryName =  "fisc-erp-connector";

    static final String PLAN_OWNER = "drajan";

    static final String PLAN_KEY = "FERPC";

    static final String PLAN_NAME =  "FISC ERP Connector - Build and Test";

    static final String DEPLOY_PLAN_NAME = "Deploy FISC ERP Connector";

    /* Bamboo global variable, for SNYK_TOKEN */
    public static final String SNYK_TOKEN = "SNYK_TOKEN";

    /* Vault variable group, which the plan will use to fetch secret used in plan vault variables*/
    public static final String vaultAccessGroup = "bamboo-finance-systems-developer-dl-mulesoft-bamboo-developers";

    /* Vault variable group for IT-Bamboo, which the plan will use to fetch secret used in plan vault variables*/
    public static final String vaultAccessGroupNonCompliant = "bamboo-finance-systems-developer-dl-mulesoft-bamboo-noncompliant";

    public static final String snykAccessGroupDev = "snyk-docker-scan-bamboo-dl-dev-access";

    public static final String snykAccessGroup = "snyk-docker-scan-bamboo-dl-snyk-docker-compliant";

    static final String BUILD_OUTPUT_FOLDER = "target/classes";

    /*Location where your maintains variable related to release versions*/
    static final String VARIABLES_PROPERTIES_FILE = "target/release-version.properties";

    /*Location where your result stored*/
    static final String JUNIT_RESULTS_PATTERN = "**/surefire-reports/*.xml";

    /*Pattern which refer to your release name*/
    static final String RELEASE_NAME = "${bamboo.inject.build.timestamp}-${bamboo.inject.git.commit.id.abbrev}";

    /* The version of centralised bamboo scripts to download */
    public static final String bambooScriptsVersion = "1.0.38";

    /* slack channel name non prod */
    public static final String SLACK_CHANNEL_NAME_NON_PROD = "#commerce-it-bo-dev-alerts";

    /* slack channel name prod */
    public static final String SLACK_CHANNEL_NAME_PROD = "#commerce-it-bo-dev-alerts";

    /* Email for notifications in case of deploy failures in PROD. eg: '<group name>@atlassian.com' */
    public static final String emailForNotifications = "commerce-it-bo-dl@atlassian.com";

    /* Team's AD group for access to the plan & deployment. eg: 'ipaas-dl-all' */
    public static final String GROUP_NAME_PERMISSION_1 = "bamboo-finance-systems-developer-dl-mulesoft-bamboo-developers";

    public static final String GROUP_NAME_PERMISSION_2 = "commerce-it-bo-dl-admin";

    /* Do not change unless image change has been requested by Build-eng */
    public static final String IT_BAMBOO_IMAGE = "docker.atl-paas.net/buildeng/agent-baseagent";

    /* Do not change unless image change has been requested by Build-eng */
    public static final String DEPLOYMENT_BAMBOO_IMAGE = "docker.atl-paas.net/sox/buildeng/agent-baseagent";

    /* Readable project name. eg: 'Hi World work flow engine' */
    public static final String SERVICE_READABLE_NAME = "FISC ERP Connector";

    public static final String DOMAIN_DEV_ENVIRONMENT = "Domain Dev";

    public static final String APP_DEV_ENVIRONMENT = "App Dev";

    public static final String STG_EAST_ENVIRONMENT = "Staging East";

    public static final String PROD_EAST_ENVIRONMENT = "Production East";

    /* ddev properties */
    public static final Map<String,String> ddevProp = new HashMap<String,String>() {{
        put("name","ddev");
        put("value","ddev");
        put("awsRegion","ap-southeast-2");
        put("integrationTestHost","https://fisc-erp-connector.ap-southeast-2.dev.atl-paas.net");
    }};

    /* ddev properties */
    public static final Map<String,String> adevProp = new HashMap<String,String>() {{
        put("name","adev");
        put("value","adev");
        put("awsRegion","ap-southeast-2");
        put("integrationTestHost","https://fisc-erp-connector--app.ap-southeast-2.dev.atl-paas.net");
    }};

    /* ddev properties */
    public static final Map<String,String> stageProp = new HashMap<String,String>() {{
        put("name","stg-east");
        put("value","stage");
        put("awsRegion","us-east-1");
        put("integrationTestHost","https://fisc-erp-connector.us-east-1.staging.atl-paas.net");
    }};
    /* ddev properties */
    public static final Map<String,String> prodProp = new HashMap<String,String>() {{
        put("name","prod-east");
        put("value","prod");
        put("awsRegion","us-east-1");
    }};

    public static final Map<String,Map<String,String>> envList = new HashMap<String,Map<String,String>>() {{
        put(APP_DEV_ENVIRONMENT,adevProp);
        put(DOMAIN_DEV_ENVIRONMENT,ddevProp);
        put(STG_EAST_ENVIRONMENT,stageProp);
        put(PROD_EAST_ENVIRONMENT,prodProp);
    }};

    /* stash token */
    public static final String stashToken = "finsys_stash_token_password";

    /* confluence token */
    public static final String confluenceToken = "finsys_confluence_token_password";

    /* bamboo token */
    public static final String bambooToken = "finsys_bamboo_token_password";

    /* Release notes name */
    public static final String releaseNotesName = "fisc-erp-connector";

    /* Confluence space key */
    public static final String spaceKey = "BSIT";

    /* Confluence parent page id */
    public static final String parentPageId = "672578733";

    /*ITAP plan URL */
    public static final String itapUrl = "https://it-bamboo.internal.atlassian.com/rest/api/latest/queue/ITAPTIN-ITBC";

    /* Project key */
    public static final String projectKey = "BPF";

    /* flag to enable/disable release notes */
    public static final Boolean enableReleaseNotes = true;

    /* flag to enable/disable Failing build if PR Description is not found */
    public static final Boolean emptyPRDescriptionFailBuild = false;

    /* flag to enable/disable appending the latest release notes towards the  start of the document */
    public static final Boolean latestReleaseNotesFirst = true;

}
